area/ui:
  - 'app/frontend/**'
area/templates:
  - 'app/frontend/templates/**'
area/backend:
  - 'app/backend/internal/**'
  - 'app/backend/cmd/**'
area/steam:
  - 'app/backend/steam/**'
area/assets:
  - 'app/frontend/static/**'
  - 'app/backend/webassets/**'
  - 'app/frontend/assets.go'
type/docs:
  - 'README.md'
  - 'docs/**'
type/ci:
  - '.github/**'
  - 'Makefile'
  - 'tools/**'